### PR TITLE
Feature/lsp tests update

### PR DESCRIPTION
**Pull request by teddylear**
This should hopefully be working now and not have any more intermittent failures

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
hey @teddylear might be a bit easier to use docker to try this out :)

**Comment by teddylear** [comment]
Agreed that's a better approach, sorry for so many CI runs. Ill get Dockerfile working.

**Comment by ThePrimeagen** [comment]
Hah!  Do not worry my friend.  I was more just commenting because the turnaround time has to be 3 minutes each attempt, that would drive me nuts.

**Comment by ThePrimeagen** [comment]
@teddylear !!!! It worked!!!!!!!

**Comment by teddylear** [comment]
Not sure why other PR is failing, going to rebase here.

**Pull request merged**
