### PR TITLE
Use vim.ui.input instead of vim.fn.input

### PR DESCRIPTION
**Pull request by IndianBoy42**
This is a draft PR, needs some architectural changes to `Pipeline` due to the new api of `vim.ui.input`

### CODE REVIEW

**Comment by IndianBoy42** [comment]
The hard part is that `vim.ui.input` returns the input through the callback and not the return value of the function itself like `vim.fn.input`. This is kinda incompatible with the  linear/blocking pipeline style architecture

This file [https://github.com/ThePrimeagen/refactoring.nvim/blob/master/lua/refactoring/refactor/119.lua] for example. Everything after the `get_input` has to be moved into a function that may be called later. Which means i can just `return true, refactor` from here to fit it into the pipeline.

Similar problems with `create_file.from_input` ([here](https://github.com/ThePrimeagen/refactoring.nvim/blob/master/lua/refactoring/tasks/create_file.lua), [here](https://github.com/ThePrimeagen/refactoring.nvim/blob/c3fea5e8b377b07cd744579f8ca65e3f805ddaad/lua/refactoring/refactor/106.lua#L134))

**Comment by IndianBoy42** [comment]
Actually I noticed the Pipeline already runs inside `async.void` so I can probably make `get_input` be an async function then nothing else has to change

**Comment by IndianBoy42** [comment]
This seems to work now, either using the inbuilt `vim.ui.input` which is the same as `vim.fn.input` or using my custom one here:

https://github.com/IndianBoy42/LunarVim/blob/master/lua/lv-ui/input.lua

**Comment by ThePrimeagen** [comment]
@IndianBoy42 this is why I made sure it ran in an async loop.  it completely helps!  But I just realized that I forgot some of these things and now I have dumb things in my code :)

I'll look at this shortly.

Addresses : #120

**Comment by ThePrimeagen** [comment]
Well done.  Thanks for the contribution!

**Pull request merged**
