### PR TITLE
feat: Adding python support for 106

### PR DESCRIPTION
**Pull request by teddylear**
Adding python support for extract function. Had to change `end_col` for `to_ts` for `Region` Class so that scope was correct for python. This is mentioned in a comment at the top of `Region` class. Appears to not have broken tests for region that exist, let me know if you want to update to something else.

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
config.lua is going through a slight refactor.  There is going to be some merge conflicts.

Resolve this and I'll merge it before any other changes. :)

**Comment by teddylear** [comment]
Resolved conflicts and ran tests again. Should be good to go, let me know if there are other issues.

**Comment by ThePrimeagen** [comment]
did you run the region tests?

**Comment by teddylear** [comment]
Yes looks like they pass still: 
image

Are you seeing errors?

**Pull request merged**
