### PR TITLE
Changing how to handle indentation (most of the time)

### PR DESCRIPTION
**Pull request by TheLeoP**
I deleted the code_generation indent module in favor of a centralized indent module. This module isn't language deppendat (i.e. use tabs for go and spaces for lua) but buffer deppendat (i.e. it works based on the settings of the buffer being edited). This means some tests had to be changed to match the default Neovim settings (or at least the default settings using the minimal_init.vim) for that filetype.

This solves some problems like a "memory leak" previously mentioned on #34 (or at least similar to it) that turned out to be an infinite whlie loop because `shiftwidth` was being used to determined the size of the indentation in a file that used tabs and had `shiftwidth=0` (apparently, dividing by 0 in lua is equal to infinity, therefore the endless while looop).

Also, I created an heuristic to define the indentation of a Point using treesitter based in the last non-blank line before and after the cursor. This new method works great for 119, printf and print_var (even if the cursor is in a line with no indent but in a function with indent or inside multiple nested indent statements) , but sadly it doesn't work that well for multiline edits like the ones on 106 (so I didn't change how it handles indentation in any mayor way).

Lastly, I added a bunch of type anotations to improve the DX.

### CODE REVIEW

**Comment by TheLeoP** [comment]
Hey. So, it's been a while since I created this PR. Is there something I could do to improve it or help it get merged? I wasn't sure if I should work on other PRs until receiving some feedback on this one, but maybe I could focus on some other small PRs (?)

**Comment by teddylear** [comment]
@TheLeoP Hey sorry I haven't gotten a chance to review. I'll try to get around to reviewing this week. Thank you again for raising the pull request for the plugin!

**Review by pranavrao145 — APPROVED** [review]
Thanks for taking the time to make this PR! I do apologize for the (very) late review; things have been quite hectic for the past several months. Personally, I think the centralized indent module independent of codegen or the language is very much cleaner, and I appreciate you taking the time to go through the codebase and refactor all of that. While it does look good to me, I had very little to do with the writing of the specific indent mechanisms for this plugin, so before I merge this I would like to get @teddylear's opinion on the same. Once again, thanks for your contribution, and sorry for the late review.

**Comment by teddylear** [comment]
Sorry again for the late review, good to merge.

**Pull request merged**
