### PR TITLE
Fix 123 for single character variable names

### PR DESCRIPTION
**Pull request by pranavrao145**
Fixes inlining issues for single-character variable names, as described in #343.

As it turns out, the changes in #347 fixed a whole bunch of stuff in terms of indenting, but broke this one very specific case when converting to an LSP range. I've just added in a check for this special case to manually reset the text_edit generated for inline var, instead of trying to mess with the region functionality. 

@teddylear take a look and let me know what you think - not sure if there's a better way to do this.

### CODE REVIEW

**Comment by teddylear** [comment]
@pranavrao145 Hey! Sorry haven't gotten a chance to review this with the holidays. I'll try to review this early this week. Hope you're having a wonderful holiday season

**Comment by pranavrao145** [comment]
Of course, no worries at all - happy holidays to you as well!

**Review by teddylear — APPROVED** [review]
Looks good 👍 , not sure if there's a better way to handle the special case. It alsot shouldn't come up often so I'm good to leave there with comment. Good to merge when you are.

**Comment by pranavrao145** [comment]
Awesome, thanks!

**Pull request merged**
