### PR TITLE
:Refactor command (with preview) and a breaking change for 123

### PR DESCRIPTION
**Pull request by TheLeoP**
I'm not entirely sure about how to handle this PR/breaking changes. So, I'm opening this to kind of ask everyone what do they think.

The big things in this PR are:

1. It adds a `:Refactor` command that accepts the name of a refactor as first argument and optionally some text as second argument (as input for 119 and 106). The command supports autocompletion for the refactor names and it previews the changes (as mentioned on #317).
2. It modifies how `123` works, introducing a breaking change to it. Before, there was a bug where, if a valid visual selection for `123` was made and then the user attempted to use `123` on a different part of the file on normal mode, the range of the first visual selection would be used. In order to solve this, I separated `123` in `inline_var_visual` and `inline_var_normal` and exported a function that calls one or the other depending on the user current mode. But, this would mean that the keymap for `123` can no longer be made with `:lua`  or `<esc><cmd>` at the beggining of it (because the plugin would always detect that the user is in normal mode and the plugin would never call the visual mode variation of `123`). I tried to minize the surface of this breaking change by doing the behaviour of `123` as similar as what a user would expect even if they don't change their mappings for `123`. But, since I have never dealt with breaking changes before, this is a new terrain for me.

In order to implement `1`, there was a blocker (mentioned on #317). I talked to one of the maintainters of `nvim-treesitter` and they told me that they are not sure about how to handle the `locals.lua` module in the future since `nvim-treesitter` does not use it. I asked if it was ok to copy the code of the `locals.lua` module into this plugin and they told me that I could do it, I just had to make it clear on both the commit message and put a comment at the top of the file stating it. I'm a bit unclear about how the licensing thing would work in this circustance; so, if someone has some knowledge on it, I would appreciate it (`nvim-treesitter` uses the Apache 2.0 Licencse). 

After copying `locals.lua`, I opened #395 since I'm not sure if using an approach more similar to the one used on other treesitter related plugins would make sense in this plugin (storing captures on `foo.scm` files and then using them with `vim.treesitter.query.get('some-lang', 'foo')`). I added a first capture to make `php` refactors work as expected because `nvim-treesitter` does not have any captures for variable definitions in the case of `php`. I'm not 100% sure about this approach, it may be better to have our own query name (instead of using `locals.scm`, we could have something like `refactor.scm`), but it would imply not relying on the upstream captures of `nvim-treesitter` (maybe we could do both?).

(After copying `locals.lua` (into `ts-locals.lus`) I deleted `ts.lua` since the functions there were just wrappers around `locals.lua`)

Some minor changes of the PR are adding even more type anottations, some minor refactors (remove all the code using `nvim-treesitter` since now there are `vim.treesitter` alternatives or the copied `ts-locals.lua` module), adding a bunch of nil checks where `lua_ls` told me they where needed, and a small fix to make `Config:reset` work as expected.

(Sorry for grouping together so many things in a single PR, I'm also not sure about how to handle that)

### CODE REVIEW

**Comment by TheLeoP** [comment]
Huh, does someone know why the exit code of the tests is 2? It looks like all of the test are passing

**Comment by pranavrao145** [comment]
Hi @TheLeoP. I have replied to you in #395 with respect to the query files and `locals.lua`. As for the rest, I will try this out, review within the next few days and let you know; after that you can merge it whenever you're ready!

**Review by pranavrao145 — APPROVED** [review]
Hi @TheLeoP. Sorry for the delayed review. I tested all of the functionality, and it seems to be all good! I just had some minor feedback:

1. The `:Refactor` command seems to show some duplicate functions. For example, it shows both `106` and `extract`. I was thinking we should maybe just keep the word versions to be consistent with the other methods of invoking refactors in this plugin. Also, there's the problem of certain modules like `106` having multiple actions like `extract_block` and `extract_to_file`, so just using the numbers might be confusing with respect to which one.
2. For `inline_var`, I see what you mean by not being able to start binds with `<Esc>` or `:lua`. There's some contradicting information in the README right now (from the old inline var) - could you just change that to reflect the new way to make the bindings? Furthermore, if you want, you can mark the breaking change commit as such by including "breaking change" in the commit header or body; this makes it show up in packer and (maybe?) some other package managers as well. I don't know how many users will actually read the breaking change even if it's highlighted by the package manager, but they'll probably get the message when they realize a bind isn't working. You don't have to do that if you don't want to, it's just a suggestion. This plugin is still very much in development so I guess such changes are expected. Maybe later on we can start an issue that tracks these breaking changes. 
3. As for copying `locals.lua`, from my understanding if you have followed the conditions the original authors have given you (which you have), it should be fine.
4. #395 covers the `.scm` file question.

Overall, thanks for the contribution - I think this change is something a lot of people were waiting for. Good to merge whenever you think it's ready.

**Comment by TheLeoP** [comment]
@pranavrao145

1. Makes a lot of sense. Now only named suggestions are given.
2. I updated the README and slightly modified all refactor and debug operations to handle exiting visual mode inside the plugin (this opens posibilities like using the same mapping for normal and visual mode on `print_var` seamlessly from the end user perspective).

**Pull request merged**
