### PR TITLE
Improve test structure

### PR DESCRIPTION
**Pull request by alvarotroya**
At the moment, all tests are placed under `lua/refactoring/test`. The naming convention of files makes it difficult to write new tests (e.g. for the same refactor strategy) and is not scalable in the long run. This PR adds substructure to the test directory to separate the tests by refactor strategy, language and test (the latter is necessary to write multiple tests for the same refactor strategy).

The new directory structure looks like this:
```
[~/repos/myrepos/refactoring.nvim/lua/refactoring/tests]$ tree
├── minimal.vim
├── query_spec.lua
├── query.ts
├── refactor
│   ├── 106
│   │   └── ts
│   │       └── example
│   │           ├── extract_var.example.expected.ts
│   │           ├── extract_var.example.inputs
│   │           ├── extract_var.example.start.ts
│   │           └── extract_var.example.ts.commands
│   └── 119
│       ├── go
│       │   └── simple-function
│       │       ├── extract.simple-function.expected.go
│       │       ├── extract.simple-function.go.commands
│       │       ├── extract.simple-function.inputs
│       │       └── extract.simple-function.start.go
│       ├── lua
│       │   └── simple-function
│       │       ├── extract.simple-function.expected.lua
│       │       ├── extract.simple-function.inputs
│       │       ├── extract.simple-function.lua.commands
│       │       └── extract.simple-function.start.lua
│       ├── py
│       │   └── simple-function
│       │       ├── extract.simple-function.expected.py
│       │       ├── extract.simple-function.inputs
│       │       ├── extract.simple-function.py.commands
│       │       └── extract.simple-function.start.py
│       └── ts
│           └── simple-function
│               ├── extract.simple-function.expected.ts
│               ├── extract.simple-function.inputs
│               ├── extract.simple-function.start.ts
│               └── extract.simple-function.ts.commands
├── refactor_spec.lua
├── region_spec.lua
```
I had to make only a single change to `refactor_spec.lua` for this to work: add a method to get the refactor strategy name from the path. I am not sure if you want to keep the 'refactor numbers/ids' forever but if not, this should be an easy change in the future.

With these changes, it should be much easier to add tests, which is what I actually wanted to do ^^

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
While we are at it, wanna drop the name of the test from the file name since its in the directory name?

**Comment by ThePrimeagen** [comment]
Also huge thanks @alvarotroya for all the recent help.  Love the clean up going on here

**Comment by alvarotroya** [comment]
I have renamed the files and introduced some variables for readability. We should definitely revisit this, there is a lot of duplicate logic for the empty test files. With the new test structure we should be able to move them into their own test case but we then need an assert callback to test the error messages. Will try to take a look into this later on

**Comment by alvarotroya** [comment]
We could also think about the general structure of tests, maybe we should extract an interface for the test data and create a singleton object to run them

**Pull request merged**
