### PR TITLE
Updated support for Ruby

### PR DESCRIPTION
**Pull request by olimorris**
Firstly, I want to say thank you to [mcritchlow](https://github.com/mcritchlow) for the [initial pull request](https://github.com/ThePrimeagen/refactoring.nvim/pull/134).

This pull requests builds on that substantially and adds **106** and **119** support. I'm keen to support this moving forward (one of my passions is adding increased support for Ruby in Neovim) and feel it's best to just ship it and add **123** support later.

Edit: Now with full **debug operations** support

Edit: Now with **123** support for single variables (working on additing multiples)

### CODE REVIEW

**Comment by otavioschwanck** [comment]
Awesome, i hope to see this on master soon!

**Comment by olimorris** [comment]
Hey @pranavrao145 @teddylear. Would love your thoughts and feedback on the above pull. Appreciate adding another language into the plugin is a big step and I am willing to offer support for any Ruby issues that arise.

**Comment by otavioschwanck** [comment]
Extract function not working:
image

Tried to extract:
```
      filename = file[:filename]
      content_type = MIME::Types.type_for(file[:filename])[0].to_s
```

Extract function to a file is working (but dont add the parameters)

Extract variable throws an error

Extract variable inline throws an error

**Comment by olimorris** [comment]
Thanks for testing. There's going to be a few of these gotchas.

For each error, can you share the ruby code before the refactor, what you expected and what you got. I can turn that into a test case which we can forever test against.

**Comment by teddylear** [comment]
@olimorris Thanks for the contribution! Sorry it took a while to review, but this looks good to me so I'm down to merge. 

@otavioschwanck Thanks for testing this! If there are some errors please create a separate issue for each with code examples so that we can add test cases and resolve.

**Pull request merged**
